### ISSUE TITLE
Re-work the theme system

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpack#102]
It will allow themes to be used in editor tools.

I hope you like going knee-deep into wpf.

**Comment by SigmaTel71** [comment]
I'm sure that I'll be involved into that. :thonk:

**Comment by Willster419** [comment]
Latest thoughts on it:
- Should use resourceDictionary and dynamicResource for color lookup
- Keep using color set classes

I'll elaborate on the current system soon tm

**Comment by Willster419** [comment]
see https://github.com/Willster419/RelhaxModpack/issues/119
