### ISSUE TITLE
Database translation project

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpack#106]
Add the ability to include translations into the database. Each package has a `UID`. We could use that for translations.

Current thought is to have a separate xml document(s) system that could be tracked in the Database repo. It would continue to be simple text. It would also include a translations editor utility inside the modpack.

**Comment by Willster419** [comment]
@SigmaTel71 in case you want to track this

**Comment by SigmaTel71** [comment]
Sure I will!

**Comment by Willster419** [comment]
Actually I'll include @elektrosmoker @123Gauss @dirty20067  @LordFelix @Nullmaruzero @Toshiro-Relhax , given that they would be the primary users. Just in case.

**Comment by Willster419** [comment]
This doesn't seem feasible, given that it would require a lot of translation work.
