### ISSUE TITLE
Dowload/update window does not exit after canceling operation

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#113]
# **Describe the bug**
Window doesnt exit after a cancel

# **To Reproduce**
hit upload zip, then hit cancel

# **Expected behavior**
window should exit when user cancels operation

# **Screenshots**
N/A

# **PC info (please complete the following information):**
N/A

# **Modpack Version**
- Modpack version 1.1.4.0

**Comment by Arkhorse** [comment]
Fixed with c8227281dab13ee668192055a928921aa6983a29

**Comment by Willster419** [comment]
https://github.com/Willster419/RelhaxModpack/releases/tag/1.3.1.0
