### ISSUE TITLE
Close some dialogue windows by Escape button

### ISSUE THREAD

**Issue by SigmaTel71** [Willster419/RelhaxModpack#115]
Some windows like News Viewer, Diagnostics, View Credits and Color Picker can be closed by pressing Escape button. This would be faster than pointing the cursor to Close button on the title bar.
I don't think that this would be a good idea to implement this feature on mod selection window, but some kind of "trigger lock" asking if the user wants to save his configuration, install selected mods (or both), cancel the installation or continue mod selection.

![image](https://user-images.githubusercontent.com/17989678/96353383-0d77d380-10d4-11eb-9ec3-ab8e6af6faa5.png)

**Comment by Willster419** [comment]
@SigmaTel71 great idea, I've made the base implementation with https://github.com/Willster419/RelhaxModpack/commit/a9e543db77930fe97e4c795352db77da557fc7f6

So far, my thoughts for windows of which should have this behavior (includes the list you started) is:

- News Viewer
- Diagnostics
- Credits
- Install finished
- Developer Selections Viewer
- Color Picker
- Preview
- Scaling Confirmation (it would be a "no" return value)
- Selection issues display

Can you think of any others?

**Comment by SigmaTel71** [comment]
"Update Available" window should also have an option to close by Escape key.
![image](https://user-images.githubusercontent.com/17989678/114268700-2752fd00-9a0b-11eb-8d97-52b68c6ff5cb.png)

**Comment by Willster419** [comment]
I guess, but I assumed not because the update window is "special", it's a yes or no, but you don't really get to advance past no :)

Perhaps though

**Comment by Willster419** [comment]
done with https://github.com/Willster419/RelhaxModpack/commit/6d488fc3a6994bf3d10e16924d54cf83e011cd49

in beta soon ™️

**Comment by Willster419** [comment]
fixed in release https://github.com/Willster419/RelhaxModpack/releases/tag/1.3.1.0
