### ISSUE TITLE
Add a "load from" setting in modpack toolbox for database things

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#121]
# **Is your feature request related to a problem? Please describe.**
No problem. Just QoL

# **Describe the feature you'd like**
Add a setting to load from the database.xml for the database output, and anything else it may be used for.

# **Describe alternatives you've considered**
None

# **Additional context**

**Comment by Willster419** [comment]
i don't understand this question. There already is a feature to load from database.xml

**Comment by Arkhorse** [comment]
There is, but you must find the file manually everytime. What I am talking about is like the database feature. Where you define where the file is.

**Comment by Willster419** [comment]
I'd rather not to be honest. That feature is a "common feature" for loading the database in all buttons in a process flow that have a "load database". It works fine as it is.

If you want to, have at it.
