### ISSUE TITLE
Proper New Language Translation Handler

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#123]
# **Describe the feature you'd like**
Some form of function within the modpack that will add a new language, with all current codes. Of course for each entry it would say "Translation Needed". A single text entry box would be needed for the actual language name. 

# **Additional context**
This would allow for anyone to add a language, without needing to do the tedious process of adding all the language.add stuff. This could also be used when we (by we I mean the Application Team) add things that need translations. Could even be used for the database object translations.

**Comment by Willster419** [comment]
I'm not certain this would be needed. What should be done at the least, however, is to make `Translations` class a partial class to allow for another file with the same class name.

But if you really wanted to, i could see you being able to do it TBH. All you'd need is:
- In the modpack toolbox, create a button to generate a new language file
- Load translation hashes if not already loaded (see unit tests for how-to)
- Use a `StringBuilder` to put:
  - The namespace
  - The partial class definition
  - The method name
- Then using `StringBuilder`, you can loop to add similar comment-like formatting, maybe include the english one, and then create a line with the `language.Add(TranslationNeeded);` and you're done.

Piece of cake!
