### ISSUE TITLE
Editor crashing when attempting to load database.xml

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#127]
# **Describe the bug**
Attempting to load the database in the editor causes a CTD. I cant even change the install location for the xml.

# **To Reproduce**
Load the editor, attempt to load the database.xml

# **Expected behavior**
should load the database

# **Screenshots**
N/A

# **PC info (please complete the following information):**
 - OS: Windows 10

# **Modpack Version**
- Modpack version 1.2.1.0

# **Logs (Required)**
[RelhaxModpackLogs_2020-11-21_18-19-30.zip](https://github.com/Willster419/RelhaxModpack/files/5578514/RelhaxModpackLogs_2020-11-21_18-19-30.zip)

**Additional context**
This only started after updating the application. Github also could not find the database folder. Had to reclone it.

**Comment by Arkhorse** [comment]
This has to do with the application deleting parts of the first three xmls (database, globaldependencies, dependencies)

**Comment by Willster419** [comment]
@Arkhorse is this still an issue?

**Comment by Arkhorse** [comment]
Yes, this can still happen occasionally. Happened when I did my last commits...
