### ISSUE TITLE
Add a minimalist setting

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpack#132]
only installs the minimum required packages and mods/dependencies needed. Request from some people inside the relic community.

**Comment by Arkhorse** [comment]
Wouldnt this be handled by a selection file?

**Comment by Willster419** [comment]
yes and no.

The request is that a user can, from the main window's settings, enable a "minimialist mode" so it doesn't include stuff they don't want. The prime example here is some of the global dependencies. While most people like the relhax loading animation and background, some don't want to install it and are of the belief they only want the minimal amount of required files. I could see this justified for a couple other packages as well in globals (and i think a couple dependencies).

What i see currently, is an xml list tracked here, but put into the managerInfo.dat file (or somewhere else) as a list of packages to exclude from install.

Yes, i know they can be disabled by using the "standard wg" files, but those go into res_mods / mods. What is being asked is to install as little files as possible.

**Comment by Arkhorse** [comment]
Ok. Why not make it so such files are never to be globals, rather default checked? And then just add a button that is default on in the selections window, to install default packages?

**Comment by Arkhorse** [comment]
Sounds alot easier to do than make something new. The load for default packages would need to have a condition check added, and our database adjusted

**Comment by Willster419** [comment]
i think from our last discussion (a long time ago), we had decided to make them global dependencies. it would be easier to make them into `default_checked.xml`, but the reasoning (i think) is that the default checked only happened when the mod selection list is brought up, without auto-loading a selection file, or using the "last installed config" file.

If we were to consider this option, i'd like to include @elektrosmoker into the discussion

**Comment by Arkhorse** [comment]
hmmm. How exactly do they want this done? Without using the mod selection window?

**Comment by Willster419** [comment]
correct. an option under installation settings for "minimalist mode". Shouldn't be too hard.

**Comment by Arkhorse** [comment]
Yeah, not that difficult. Wonder if we could include the other option as well

**Comment by Willster419** [comment]
include an option to toggle inclusion of "default checked" mods

**Comment by Willster419** [comment]
Initial implementation done with https://github.com/Willster419/RelhaxModpack/commit/7e7cc5aaea3603423e09fc9045ce30eaab15c125

**Comment by Willster419** [comment]
added in release https://github.com/Willster419/RelhaxModpack/releases/tag/1.3.1.0
