### ISSUE TITLE
appCrash when editing globalDeps

### ISSUE THREAD

**Issue by elektrosmoker** [Willster419/RelhaxModpack#133]
# **Describe the bug**
Application crash when opening the selection window from main window - after renaming/moving globalDependencies.

# **To Reproduce**
- a globalDep got removed [DependencyGlobal_RelHax_LoadingSplash] https://github.com/Willster419/RelhaxModpackDatabase/commit/db9ccdb12af6c3c939b482114b7d68508091517e
- another one got renamed to the name of the removed pkg https://github.com/Willster419/RelhaxModpackDatabase/commit/68b0eed5480c20eac1debebf28b80c8f33166187

# **Behavior**
When removing a globalDependency (at least the *_LoadingSplash from above) the installer will not load the selection window and will crash.

I found out that it has something to do with the lastInstalledConfig.xml - when you remove it, the installer will not crash and load the selection window.
Since we track changes to selection files, can it be that this conflicts with globalDeps? 
Do we need them in selection files?

# **Logs**
attached
[Relhax.log](https://github.com/Willster419/RelhaxModpack/files/5673273/Relhax.log)

**Comment by Willster419** [comment]
oh. should have read this before i published 🤦‍♂️ 

fixed in https://github.com/Willster419/RelhaxModpack/releases/tag/1.2.4.0
