### ISSUE TITLE
Add a check when doing database update for media

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#134]
When performing a DB update, have the toolbox parse the media for all packages, and determine if they are valid. This should help us ensure all media works. 

Maybe you could make it so it keeps a list of master domains, and it parses those first? Any domain that doesnt work, would also prevent all media from working.

**Comment by Willster419** [comment]
This is a good idea

**Comment by Willster419** [comment]
I'm thinking this can be a simple check to:
- Load the database
- For each `SelectablePackage`, For each `Media` where type is image or audio
- Attempt to download it.

The question becomes what to do if it fails. For starters, we'd want to log it of course. But do we want to  additionally remove the offending medias? Or just log it? Or allow for a user update?

Thoughts?

**Comment by Arkhorse** [comment]
Well, if it was in the editor, rather than the toolbox, it could just open the offending package to the media tab, and if possible, flash the offending entry. Sadly I dont know of a way to test the webpage one...

Also, can the media _combobox_ have a default to image?

**Comment by Willster419** [comment]
I think this is done with https://github.com/Willster419/RelhaxModpack/commit/8a0bfdc638237ee11d7dec3afdc49e8de00a064f

Check it out:
![image](https://user-images.githubusercontent.com/2482828/115224604-ebcac980-a0c1-11eb-8582-7410f62a6b2a.png)

**Comment by Willster419** [comment]
added in release https://github.com/Willster419/RelhaxModpack/releases/tag/1.3.1.0
