### ISSUE TITLE
Clicking save after adding dev url crashes editor

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#136]
# **Describe the bug**
I added a dev url to a mod I am adding, clicked save, and then the crash window showed up.

# **To Reproduce**

Add a dev url, click save. Error might show up. 

# **Expected behavior**
Expected to save...

# **Screenshots**

# **PC info (please complete the following information):**
Windows 10, 2004

# **Modpack Version**
1.2.4.0

# **Logs (Required)**
[RelhaxModpackLogs_2020-11-21_18-19-30.zip](https://github.com/Willster419/RelhaxModpack/files/5720115/RelhaxModpackLogs_2020-11-21_18-19-30.zip)

**Additional context**
I had the editor open for quite some time, adding/changing mods in the TankSkinsRemodels category.

**Comment by Willster419** [comment]
@Arkhorse is this still an issue?

**Comment by Arkhorse** [comment]
Im not sure. I havnt done such long sessions in a while
