### ISSUE TITLE
add a textfield to the modselection window that shows the current database version/name

### ISSUE THREAD

**Issue by elektrosmoker** [Willster419/RelhaxModpack#137]
# **Is your feature request related to a problem? Please describe.**
People may have chosen the wrong database branch when using the beta-database. In some cases the installation can fail or the game client can break then.

# **Describe the feature you'd like**
A simple field with colored text (an alerting color!) with the current branch´s name in the modselection window. 
This should only be seen when the beta-db is selected (or put the public database´s version here).

# **Describe alternatives you've considered**
A popup when entering the selection window. But this may be annoying for people who use the beta db all the time. I dont think this is a real alternative...

![2020-12-26 17_43_30-](https://user-images.githubusercontent.com/40739360/103155708-69c93480-47a2-11eb-9c6b-682ede52ec8e.png)

**Comment by Willster419** [comment]
How's this for an implementation?
![Stable](https://i.imgur.com/OJJSyg8.png)
![Beta](https://i.imgur.com/TpOUX6R.png)

Stable will show the specific version of the db installing, beta will show the branch, test will show `TEST` again.

**Comment by Willster419** [comment]
fixed in release https://github.com/Willster419/RelhaxModpack/releases/tag/1.3.1.0
