### ISSUE TITLE
move the default mirror urls to be https

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpack#139]
and while you're at it can you add the mirror support pls and thank

**Comment by elektrosmoker** [comment]
don't get lost behind the mirrors, alice!
![image](https://user-images.githubusercontent.com/40739360/107543365-73c7bb00-6bc9-11eb-8758-536ea5b842c3.png)

**Comment by Willster419** [comment]
superseded by https://github.com/Willster419/RelhaxModpack/issues/140
