### ISSUE TITLE
Automation: clear button for the selected sequences list

### ISSUE THREAD

**Issue by elektrosmoker** [Willster419/RelhaxModpack#161]
as title says, plz

**Comment by Willster419** [comment]
you mean to remove selected sequences?

![image](https://user-images.githubusercontent.com/2482828/130125167-166a3d4f-6db8-4c8d-97ac-e96740df84dc.png)

if you wanted to remove all of them, you can ctrl + a, then click the button

(i admint, i should change the text from "delete", to "remove")

**Comment by elektrosmoker** [comment]
meh, shortcut keys. i hoped you help promote laziness.  :) 

and yes, i wanted to clear the whole list.

**Comment by Willster419** [comment]
ah, use the physical key delete. understandable.

i'll see what i can do 🔜

**Comment by Willster419** [comment]
done with https://github.com/Willster419/RelhaxModpack/commit/952bf311a54dc3521902f1f1389a228eda07d18d
