### ISSUE TITLE
automationRunner sometimes not updating the database xml file

### ISSUE THREAD

**Issue by elektrosmoker** [Willster419/RelhaxModpack#162]
sometimes i need to run a sequence twice to be able to do a database commit. 
at first run the program does not write any information into the database, although it uploads the file correctly and i cant see anything wrong in the log. 

it happened now with the [6thSense_Timer] sequence.
log attached, it is the last two runs (don´t mind the errors/web exceptions)
[RelhaxAutomation.log](https://github.com/Willster419/RelhaxModpack/files/7061379/RelhaxAutomation.log)

**Comment by Willster419** [comment]
fixed this a while ago, it was how the save behavior was being handled after a run
