### ISSUE TITLE
Installer won't start

### ISSUE THREAD

**Issue by skranz1982** [Willster419/RelhaxModpack#4]
Hi guys,

I can't run the installer. Download seems to be fine, but when I click it, nothing happens. Even the Task Manager does not show the process. Can you reproduce this error?

Best,
seb

**Comment by Willster419** [comment]
I have never had a problem where the application does not start after clicking it. What OS are you running? Does the application create a "RelHaxLog.txt" file in the directory where the exe is?

**Comment by skranz1982** [comment]
Hey

* I'm running win10 Pro x64.
* Nope, no relhaxlog.txt
* Running as admin won't start it either.

**Comment by Willster419** [comment]
That is interesting. Of all the C# applications I've built, I've never had this problem, of it just "not starting".
What anti virus do you have? Have you tried disabling it?
If you have a vm of windows xp, 7, 10, etc, try launching it in there?
I would also try doing a repair/reinstall of .net framework components. (4.0, 4.5)

**Comment by skranz1982** [comment]
I'm using "360 Total Security" and yes, I disabled it - without success.
I'll check on my computer at work tomorrow. It's also win 10 x64 Pro but a complete differently setup. Also, I have a VM with win7 there.

I'll try the RepTool later on and give you some feedback.

**Comment by Willster419** [comment]
Also just to make sure we are talking about the right files, you downloaded by:
Going to this link: https://github.com/Willster419/RelhaxModpack
clicking to "skip to download link"
click the download link
you then download a file called RelhaxModpack.exe
correct?

**Comment by skranz1982** [comment]
Yepp, I downloaded the files from your adfly site. I've tried the direct link, also - both with no effect.

**Comment by Willster419** [comment]
What was the result of trying it on your work computer, and/or your window 7 vm? Did you try running the framework repair, or reinstalling them?
I have also found that you need Windows installer 3.1, but that should come standard with every new windows installation since windows 7.
Again, I have never had an issue like this. So far it seems to be an isolated case with your computer, and I so far can't replicate it on any of my computers. Let me know what the results are.
I will do some advanced reseearch as to why this is happening.

**Comment by Willster419** [comment]
I have done some research and think it may be an assembly related issue on your computer. (.net framework is missing/corrupted files)
Please try running the latest version of the modpack (21.7.2) and see if it creates any log output.

**Comment by skranz1982** [comment]
Hello again,

my Win 10 Pro x64 at work did a lot of stuff, especially delivering errors ^^ 
1. a warning: this may be a dangerous file
2. a message: "new version available" - I can't download it though, because our proxy requires authentication
3. an error: "not supported 16bit application"

Your updater created a lot of files and folders - here's the content of the relhaxlog.txt:
|------------------------------------------------------------------------------------------------|
Main Entry point launched
Loading translation hashes
Attempting to load MainWindow
MainWindow Constructed
|RelHax Modpack version 21.7.2
|Built on 04/20/2017, running at 21.04.2017 09:22:42
|Running on Microsoft Windows NT 6.2.9200.0
Successfully made single instance text file
Starting check for application updates
exe is out of date. displaying user update window
User accepted downloading new version
New application download started
Loading settings
Loading application settings
WARNING:Settings xml not found, loading defaults
Settings loaded sucessfully
FirstLoadHelper: startup location is x: 2011, y: 26
Saving application settings
Settings saved sucessfully
Application Closing
|------------------------------------------------------------------------------------------------|

My win7 Pro x64 VM (which is in another domain) also asked me to update and then gave me that "proxy auth" error. The logfile is identical expect for...
* running time
* windows version
* startup location.

**Comment by skranz1982** [comment]
No worries, Willster. I'm a software developer myself and know how hard it can be at times... You have all my support.

I did not yet succeed at repairing/reinstalling those .NET redists as I have to find out which version's installed on my computer at home first. The repair tool did find some issues. I just didn't took the time to check up on everything before.

**Comment by Willster419** [comment]
I have recieved a message form someone else who has the same problem as you. He (or she) said that the solution was to set compatibility mode for Windows XP service pack 2 or 3. Try that on your home computer and see if it works. But before you try that, try running it on your home computer without compatibility and see if it creates a log file.

**Comment by skranz1982** [comment]
Hi again,

downloaded the latest version - doesn't start.
run as admin - doesn't start.
every SINGLE frigging compatibility mode down from "windows 8" to "windows 95" - doesn't start.

This is... odd. Let me check on the .NET Framework repair tool and Creator's Update also.

**Comment by Malayus** [comment]
I get the same issue didn't run in any compatibility mode but I could run it under a command com promp window (Adm. rights), weird but works for me (y)

**Comment by skranz1982** [comment]
Damn! You're right! Start it from a command prompt instantly runs the little bugger. Amazing ^^

I tried to run it from the Explorer after installing Creator's Update and(!) reinstalling .NET 3 and .NET 4.6 completely anew - didn't help.

**Comment by Willster419** [comment]
Interesting! Thanks for the input. I guess just run it from command prompt for now.
I will look into why that is the case. If it stops working from command prompt, or you can't run it with command line arguments, like "/auto-install" or "/skip-update" in command prompt, let me know, i will move it to a higher priority in our bug tracker.
Thanks again!
