### ISSUE TITLE
Mod Pack installs but crashes WOT

### ISSUE THREAD

**Issue by Xantier-KID** [Willster419/RelhaxModpack#5]
Installed the mod pack for the first time today. The installer ran great but whenever i load even a single mod like Tank Carousel 3 row. Go to launch WOT loading bar gets 2/3 across then screen goes black. Go to task manager details to analyze wait chain for WorldOfTanks.exe and i get a message that World of Tanks has stopped working. Uninstall Relhax Modpack and everything works fine. Just don't have any mods. 

Have tried this with multiple single mod installs with clean installation with the same results as above:
Bones's XVM Config
Default Config
Willster Config
battle interface total HP
XVM color 10 scale
battle results page2
clock both 12 and 24 hour
save last server
minimap disabled
Statitistics color step
battle interface mod - hitlog
battle assistant (doesn't black screen WOT just completely crashes.)

Though this process I did find some mods that did work:
Server Reticle Blue
Penetration Pmod
zoom out 500
crosshairs meltymaps mathmod
arty crosshair  harpoon
damage log omc
ballte observer
damage indicator green warrior
colored penetration artasan
in battle current rating protanki
max far plane both
number indicator of penetration
safeshot 2 sec
yasen krasen vanilla daily reset
6th sense aslan

I like this mod pack better than OMC, its a little more complicated but makes it smoother for future installations, I would like to use this as a replacement for the OMC mod pack. How can I help you?

**Comment by Willster419** [comment]
I just updated the modpack for 0.9.18. Please try it now :)
What do you mean by "How can I help you?" As in provide more debug information or are you volunteering to help maintain the modpack?

**Comment by Xantier-KID** [comment]
volunteering to help maintain the mod pack. I used to build my own up until I found OMC in its early stages. Then I would start with the OMC install and then go find the mods that OMC didn't have and would install those after. After a while OMC ended up having the extra mods I would add or a variation of them so I stopped downloading them and just used OMC because it was easier and less time consuming (usually would take me a day or two after WOT update to test new versions of mod packs and figure out what order they needed to be extracted in and that was when i wasn't so lucky and couldn't copy my old resmod folder to the new update). I had a couple of buddys that used my mod pack so i would upload it to my TS server and if they needed i would remote onto their pc and help them copy my mod pack into place.

**Comment by Willster419** [comment]
Glad to hear that it worked.

I would love the help, thanks for volunteering! We are using a slack group to maintain our communication, I need to send you the information. What is your WoT ingame/forms name so I can send you a PM? also which server? I can explain about how to modpack works and how you can help.

Yeah, there are a lot of mods that were on OMC that need to still be added to Relhax. Essentially, I am trying in a few months to get to where OMC got to after a few years. Already 250 hours into the project lol. I encourage you to use this spreadsheet for a mod request:
https://docs.google.com/spreadsheets/d/1LmPCMAx0RajW4lVYAnguHjjd8jArtWuZIGciFN76AI4/edit

After you reply to this with your ingame name in WoT, I will close this issue.

**Comment by Xantier-KID** [comment]
Xantier is my ingame i don't post on the forums

**Comment by Willster419** [comment]
Just sent you a message on the forms. Once you are added to slack we can talk more there.

Thanks for the info about TS. I have someone right now working on a discord solution, but will keep that in mind.
