### ISSUE TITLE
Greyed out options + one typo

### ISSUE THREAD

**Issue by cryohellinc** [Willster419/RelhaxModpack#6]
Hi there, i would like to say a big Thank you for this project of yours. Imo it is far better compared to OMC Modpack in terms of how it works / potential for future.

I have two questions / suggestion and a typo:

a) There are a lot of Greyed out options. Are those to be done features, or simply features unlocked with different modpack mod combinations selections? Please clarify if possible.

b) Clean Uninstallation option in installer, does it also clean in game cache?

c) Would it be possible for you to add "no gun shake" mod. 👍 

d) Below a typo, instead of Fire it says File. ;)

![capture](https://cloud.githubusercontent.com/assets/17429806/25563073/8dab88b8-2d9c-11e7-8c5c-ab78b7eac881.PNG)

**Comment by Willster419** [comment]
hello :)
a) greyed out options are mods/configs that are disabled. It is most likely broken/not updated for the latest version of tanks.
b) the clean uninstallation means that it would uninstall all mods, including those not installed by the modpack. It currently does not clear the game cache.
c) Done yesterday.
d) Will be done tomorrow.

Thanks for the support! :)
