### ISSUE TITLE
CTD: Previewing Some Contour Icons

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#67]
# **Describe the bug**
previewing contour icons causes CTD

# **To Reproduce**
Right click header of contour icon (IE: Champi's)

# **Expected behavior**
Show preview window

# **Screenshots**

# **PC info (please complete the following information):**
 - OS: Win10
 - Version [e.g. 22]: 1809

# **Modpack Version**
- Modpack version [e.g. 0.28.2.28]
1.0.0.1
# **Logs (Required)**
[Relhax.log](https://github.com/Willster419/RelhaxModpack/files/4052445/Relhax.log)

**Additional context**
Verified all related images are accessable via editor. They work fine there. Only Champi and Electrosmoker's seem to be affected

Original report: https://discordapp.com/channels/303262090741940226/303263790827307008/666176603201601536

**Comment by Willster419** [comment]
Fixed with https://github.com/Willster419/RelhaxModpack/commit/39e38c2fa5126362dd1c19ba1188f3f3eccadaee
I'll be including that into several other bug fixes this weekend.

If you want, you can always clone out and run the developer build yourself to test.

Thanks for the report.
