### ISSUE TITLE
21.8.6 causes crash

### ISSUE THREAD

**Issue by cryohellinc** [Willster419/RelhaxModpack#7]
First updater popped out ( thank you for introducing it ), updated to latest patch, and now it crashes on loading. 

Here is my config

https://mega.nz/#!8c1THTTZ!iWWxO41fgzRAcgOkpO8QhADnWJKI4DLOwOyTswAhMFY

If i delete all mods, game starts normally. Previous update all worked smooth.

Thank you for all the work!

**Comment by Willster419** [comment]
Sorry to hear it is crashing. To clarify:
The game is crashing? If so I need a python log.
Thank you for sending your config file.

**Comment by Willster419** [comment]
I fixed it. Silly error forcing a certain encoding type.
I tested it, and it seems to work.
If it still does not work, let me know.
