### ISSUE TITLE
singledropdown1 and long lists causes installer to randomly choose an option

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#88]
# **Describe the bug**
Selecting an option in a dropdown that is long (6th sense tested) causes the installer to choose a random option

# **To Reproduce**

1. Open installer
2. Start selection GUI
3. Go to 6th sense category, attempt to select an option for icons
4. See bug

# **Expected behavior**
Option chosen should be option selected

# **Screenshots**
N/A

# **PC info (please complete the following information):**
N/A - Occurs on all Windows OS's

# **Modpack Version**
- 1.1.0.7

# **Logs (Required)**

[RelhaxModpackLogs_2020-06-09_16-58-40.zip](https://github.com/Willster419/RelhaxModpack/files/4754528/RelhaxModpackLogs_2020-06-09_16-58-40.zip)

**Additional context**

**Comment by Arkhorse** [comment]
Silvers Logs:
https://discordapp.com/channels/303262090741940226/303262090741940226/720006979996614686
https://discordapp.com/channels/303262090741940226/303262090741940226/720006817609941133

**Comment by Willster419** [comment]
in case i never said it before - i hate comboboxes.

yes i can replicate the issue. scroll a bit in the long list and by clicking it will move the selection
i'll take a stab at it

in case i never said it before - i hate comboboxes.

**Comment by SigmaTel71** [comment]
I reproduced that bug on 1.1.0.7 application version, but I found pretty dumb (xD) workaround by just holding the left mouse button and scrolling to the icon you want.
P.S. I don't like comboboxes either, but in certain situations I have to use them too. :P

**Comment by Willster419** [comment]
fixed in beta for testing with https://github.com/Willster419/RelhaxModpack/commit/d544af76ca28fc7ea82d398236143b67e5e88006

**Comment by Willster419** [comment]
oh yeah i meant to close this. I fixed it in 1.1.1.0

**Comment by Arkhorse** [comment]
> oh yeah i meant to close this. I fixed it in 1.1.1.0

Soon ™️
