### ISSUE TITLE
Installer is unreadable using 4k resolution

### ISSUE THREAD

**Issue by yxhuvud** [Willster419/RelhaxModpack#9]
Please scale installer so that the text is readable without a magnifier using high resolutions. I think there are system settings that can be read or something.

**Comment by Willster419** [comment]
I have no problem doing this, but I don't have a 4k monitor to test on. Could you send me a screenshot of exactly where it is unreadable?

**Comment by yxhuvud** [comment]
I'm not certain a screenshot is worthwhile as they scale with the display, but the mod-selection-window is 11.5 cm wide on my screen, when stretched so that it show all the 15 tabs. 

Incidentally, the initial screen (with the start-selection and uninstall options) doesn't have this problem at first, but then when I hit 'start mod selection, then that window too is resized into being stupidly small.

**Comment by Willster419** [comment]
I split the scaling options into two different settings: DPI mode and font mode. Font mode scales based on window font size. DPI mode scales based on the DPI of your monitor. I also have every forum window now load these settings on startup, so all windows will now scale according to the selected setting. Does this help at all?

**Comment by yxhuvud** [comment]
DPI setting has no difference from 1x font scaling that I can see. 

The other scaling modes have text in readable size, but has other issues: [http://imgur.com/a/Ztn44](url)

**Comment by Willster419** [comment]
That is interesting. It does not do that on my pc.
If you start the installation, what does the Mod Selection List look like? There are a few autosize properties between the two that are different (by mistake), and I am curious if either of the two windows look ok.

**Comment by yxhuvud** [comment]
It is a mixed bag. The selection parts (mostly) look ok apart from the select boxes. Menues, not so much.

[Screenshot](http://imgur.com/a/oZC39)

Could it be the scaling settings in the display alternatives page that isn't applied correctly for some reason? Pulling that setting up to 250% is what makes the windows UI in general not too small, but perhaps it is applied to some but not all sizes.

**Comment by Willster419** [comment]
It seems to be an autosize issue, but I am having trouble tracking it down. Also, I have updated the application so that it uses the second DPI scaling method properly. Does that method of scaling work for you?

**Comment by yxhuvud** [comment]
Ok, that looks a lot better. Thanks!

There are still some minor issues, most notably the checkboxes: [here](imgur.com/a/Ucb16)

1.75 is still on the small side though. 

It is a bit weird that the initial launcher window is too large with the dpi scaling selected, but that it is then resized into being the same size as the other window once the mod selection is started.
