### ISSUE TITLE
Add a feature to export translations to csv

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpack#93]
One file, has the columns `ID`, `Language1`, `Language2`, etc.

List them exactly as they are loaded from source.

This shouldn't be too bad to do.

**Comment by SigmaTel71** [comment]
So I can pretend that I'm working on Excel spreadsheet but actually translating the UI? Good idea! :sweat_smile:

**Comment by Willster419** [comment]
The original idea was just to export what the application has loaded. So it's a way to identify missing translations. You would still need to update the `Translations.cs` file.

I'm open to other ideas with it.

**Comment by Willster419** [comment]
Implementation candidate completed at https://github.com/Willster419/RelhaxModpack/commit/bff65e43de7c2ac676c48344f743e59d7edf3027

It uses the delimiter as a tab, so not exactly csv. But if that's not a problem for you guys I'll roll with it.

If a translation entry is defined but blank, it's output is `TODO`. If a translation is straight up missing, it's output is `MISSING_TRANSLATION`.

You can use it for filtering like this:
![With MISSING_TRANSLATION](https://i.imgur.com/PwVDwrB.png)

![With TODO](https://i.imgur.com/ZBvE0iQ.png)

I'm looking to include with with several other fixes and features into an update roll-up for beta, tomorrow (Sunday). If there's anything missing, to change, etc. please let me know by then.
